- hosts: ldapclient
  remote_user: root

  vars:
    gid: ldapmanager

  tasks:
    - name: Yum install
      yum: name={{ item }} state=present
      with_items:
        - openldap-clients
        - sssd
        - sssd-client
        - sssd-ldap
        - oddjob-mkhomedir

    - name: sssd.conf create
      file:
        state=touch
        path=/etc/sssd/sssd.conf
        owner=root
        group=root
        mode=0600

    - name: sssd.conf write
      lineinfile:
        dest=/etc/sssd/sssd.conf
        state=present
        line="{{ item }}"
      with_items:
        - '[sssd]'
        - 'debug_level = 0'
        - 'config_file_version = 2'
        - 'services = nss, sudo, pam, ssh'
        - 'domains = default'
        - '[domain/default]'
        - 'id_provider = ldap'
        - 'auth_provider = ldap'
        - 'chpass_provider = ldap'
        - 'sudo_provider = ldap'
        - 'ldap_uri = ldap://192.168.3.6'
        - 'ldap_search_base = dc=abc,dc=def,dc=com'
        - 'ldap_sudo_search_base = ou=SUDOers,dc=abc,dc=def,dc=com'
        - 'ldap_id_use_start_tls = False'
        - 'ldap_search_timeout = 3'
        - 'ldap_network_timeout = 3'
        - 'ldap_opt_timeout = 3'
        - 'ldap_enumeration_search_timeout = 60'
        - 'ldap_enumeration_refresh_timeout = 300'
        - 'ldap_connection_expire_timeout = 600'
        - 'ldap_sudo_smart_refresh_interval = 600'
        - 'ldap_sudo_full_refresh_interval = 10800'
        - 'entry_cache_timeout = 1200'
        - 'cache_credentials = True'
        - 'ldap_tls_reqcert = never'
        - '[nss]'
        - 'homedir_substring = /home'
        - 'entry_negative_timeout = 20'
        - 'entry_cache_nowait_percentage = 50'
        - '[pam]'
        - '[sudo]'
        - '[autofs]'
        - '[ssh]'
        - '[pac]'

    - name: authconfig set 1
      shell: authconfig --enablesssd --enablesssdauth --enablelocauthorize --disableldap --disableldapauth --disableldaptls --update

    - name: homedir start
      service:
        name=oddjobd
        state=started
        enabled=yes

    - name: authconfig set 2
      shell: authconfig --enablemkhomedir --update

    - name: sshd_config edit 1
      lineinfile:
        dest=/etc/ssh/sshd_config
        backup=yes
        state=present
        regexp='#RSAAuthentication yes'
        line='RSAAuthentication yes'

    - name: sshd_config edit 2
      lineinfile:
        dest=/etc/ssh/sshd_config
        state=present
        regexp='PubkeyAuthentication'
        line='PubkeyAuthentication yes'

    - name: sshd_config edit 3
      lineinfile:
        dest=/etc/ssh/sshd_config
        state=present
        regexp='AuthorizedKeysCommand '
        line='AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'

     - name: sshd_config edit 4
       lineinfile:
         dest=/etc/ssh/sshd_config
         state=present
         regexp='AuthorizedKeysCommandUser'
         line='AuthorizedKeysCommandUser root'

     - name: sssd restart
       service:
         name=sssd
         state=restarted
         enabled=yes

     - name: sshd restart
       service:
         name=sshd
         state=restarted
         enabled=yes

     - name: edit sudoers
       lineinfile:
         dest=/etc/sudoers
         state=present
         line='%{{ gid }}  ALL=(ALL)       ALL'
         insertafter='%wheel'