- import_playbook: 01-03_host.yaml
  tags: host
- import_playbook: 02-02_selinux.yaml
  tags: selinux
- import_playbook: 02-04_defaulttarget.yaml
  tags: defaulttarget
- import_playbook: 02-05_locale.yaml
  tags: locale
- import_playbook: 02-06_timedate.yaml
  tags: timedate
- import_playbook: 02-07_kernelparam.yaml
  tags: kernelparam
- import_playbook: 02-08_yum.yaml
  tags: exclude
- import_playbook: 02-09_package.yaml
  tags: package
- import_playbook: 02-10_grub.yaml
  tags: grub
- import_playbook: 02-11_kdump.yaml
  tags: kdump
- import_playbook: 02-12_sshd.yaml
  tags: sshd
- import_playbook: 02-13_limits.yaml
  tags: limits
- import_playbook: 02-14_service.yaml
  tags: service
- import_playbook: 02-15_udev.yaml
  tags: udev
- import_playbook: 02-16_vmwaretools.yaml
  tags: vmwaretools
- import_playbook: 02-17_authconfig.yaml
  tags: authconfig
- import_playbook: 03-02_part.yaml
  tags: part
- import_playbook: 03-03_vg.yaml
  tags: vg
- import_playbook: 03-04_lv.yaml
  tags: lv
- import_playbook: 03-06_filesystem.yaml
  tags: filesystem
- import_playbook: 03-07_mount.yaml
  tags: mount
- import_playbook: 04-01_nsswitch.yaml
  tags: nsswitch
- import_playbook: 04-03_if.yaml
  tags: if
- import_playbook: 04-04_route.yaml
  tags: route
- import_playbook: 05-01_etc.yaml
  tags: etc
